name: Build next.js web app
on: push
jobs:
  build-project:
    name: Build App
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Build app assets
          run: npm run build
        - name: Upload static site content
          uses: actions/upload-artifact@v4
          with:
            name: next-static-site
            path: .next
  release-project:
    name: Download static assets
    runs-on: ubuntu-latest
    needs: build-project
    steps:
     - name: download artifact
       uses: actions/download-artifact@v4
       with:
        name: next-static-site
     - name: test artifact download
       run: ls -R

